# -----------------------------------------------------------------------------
# Rule Parameters
# -----------------------------------------------------------------------------

# These are rule-based parameterization that will apply to ALL builds.
# If a parameter is not listed here, it cannot be customized.

# name    : The rule to apply the parameters to.
# <param> : The parameter name as specified in `workflow/Snakefile`.

rule_params:

  # ---------------------------------------------------------------------------
  # tag : datestamp of dataset (run `nextclade dataset list` for more info)
  # dataset: The nextclade dataset to use as the reference
  # dataset_no-recomb: The nextcldae dataset to use without recombinants
  # tag_no-recomb: datestamp of the dataset without recombinants
  - name: nextclade_dataset
    dataset: sars-cov-2
    dataset_no-recomb: sars-cov-2-no-recomb
    tag: "2022-06-14T12:00:00Z"
    tag_no-recomb: "2022-04-28T12:00:00Z"

  # ---------------------------------------------------------------------------
  # exclude_clades    : Exclude strains that are recombinants of these clades
  - name: nextclade_recombinants
    exclude_clades:
        - "19" # From 2019

  # ---------------------------------------------------------------------------
  # exclude_negatives : true if sequences that are not recombinants (according to Nextclade) should be excluded from sc2rf analysis.
  #                   : only set to true if there is at least 1 guaranteed recombinant sequence in your input!
  # max_name_length   : The maximum character length of strain names
  # clades            : Restrict parent search to these clades
  # secondary_clades  : To detect recombination in BA.4 and BA.5, these clades must be run separately
  # sc2rf_args        : Additional arguments supplied to the program sc2rf
  # debug_args        : Ultra-sensitive arguments for debugging
  # primers           : Path to primers, relative to sc2rf directory.
  # primers_name      : The name of the primer set to display in output.
  - name: sc2rf
    exclude_negatives: false
    max_name_length: 50
    clades:
      - "20A" # Non-VOC 2020
      - "20B" # Non-VOC 2020
      - "20C" # Non-VOC 2020
      - "20D" # Non-VOC 2020
      - "20E" # Non-VOC 2020
      - "20F" # Non-VOC 2020
      - "20G" # Non-VOC 2020
      - "20I" # Alpha
      - "20H" # Beta
      - "20J" # Gamma
      - "21I" # Delta
      - "21J" # Delta
      - "21C" # Episilon
      - "21D" # Eta
      - "21E" # Theta
      - "21B" # Kappa
      - "21G" # Lambda
      - "21H" # Mu
      - "21K" # Omicron BA.1
      - "21L" # Omicron BA.2
      - "B.1.438.1" # proposed808
    secondary_clades:
      - "21K" # Omicron BA.1
      - "21L" # Omicron BA.1
      - "22A" # Omicron BA.4
      - "22B" # Omicron BA.5
    mutation_threshold: 0.25
    # Note : If you want sc2rf to update its mutation database everytime, add --rebuild-examples to `sc2rf_args`.
    sc2rf_args: "--ansi --parents 2-100 --breakpoints 0-100 --unique 1 --max-ambiguous 20 --max-intermission-length 3 --max-intermission-count 3 --ignore-shared"

  # ---------------------------------------------------------------------------
  # lapis           : If true, query cov-spectrum using LAPIS to identify parental lineages
  #                 : recommended false if number of sequences > 100.
  # min_len         : (optional) Ignore recombinants regions shorter than this
  # max_breakpoints : (optional) Exlude samples with greater than this number of parents
  # max_parents     : (optional) Exlude samples with greater than this number of breakpoints
  # motifs          : (optional, experimental) Path to a breakpoints motif file
  # lapis
  - name: sc2rf_recombinants
    lapis: true
    min_len: 1000
    max_parents: 2
    max_breakpoints:
    motifs:

  # ---------------------------------------------------------------------------
  # exclude_false_positives : true if sequences that are false positives (according to sc2rf) should be excluded.
  - name: faToVcf
    exclude_false_positives: false

  # ---------------------------------------------------------------------------
  # extra_cols : (Optional) list of metadata columns to output going forwards (aside from defaults of strain,date,country)
  - name: summary
    extra_cols:
    #  - gisaid_epi_isl
    #  - genbank_accession

  # ---------------------------------------------------------------------------
  # geo            : Column to use for a geographic summary (typically region, country, or division)
  # max_placements : The maximum number of UShER placements before labeling false_positive (-1 to disable.).
  # Note: the rule `linelist` is also going to use the `extra_cols` param of rule `usher_metadata`, to determine which metadata columns appear in the linelist
  - name: linelist
    geo: country
    max_placements: -1

  # ---------------------------------------------------------------------------
  # lag           : The number of weeks before the present where data is accurate (ex. 4). Used to plot a light grey box.
  # weeks         : The number of weeks to plot in retrospect (ex. 16)
  # min_date      : (Optional) The date to start plots at (ex. "2022-01-03"). Overrides the `weeks` parameter.
  # max_date      : (Optional) The date to end plots at (ex. "2022-04-25").
  # singletons    : "true" if singelton lineages (N=1) should be plotted and reported.
  # Note: the rule `plot` is also going to use the `geo` param of rule `linelist`, to plot recombinants by geographic location
  - name: plot
    weeks: 16
    lag: 4
    min_date:
    max_date:
    singletons: true

  # ---------------------------------------------------------------------------
  # changelog   : (Optional) path to a CHANGELOG.md to append to the report
  # template    : (Optional) path to a powerpoint template
  # Note: the rule `report` is also going to use the `geo` param of rule `linelist`, to summarize recombinants by geographic location
  - name: report
    changelog: "CHANGELOG.md"
    template: "resources/template.pptx"
