# -----------------------------------------------------------------------------
# Rule Parameters
# -----------------------------------------------------------------------------

# These are rule-based parameterization that will apply to ALL builds.
# If a parameter is not listed here, it cannot be customized.

# name    : The rule to apply the parameters to.
# <param> : The parameter name as specified in `workflow/Snakefile`.

rule_params:

  # ---------------------------------------------------------------------------
  # tag : datestamp of dataset (run `nextclade dataset list` for more info)
  # dataset: The nextclade dataset to use as the reference
  # dataset_no-recomb: The nextcldae dataset to use without recombinants
  # tag_no-recomb: datestamp of the dataset without recombinants
  - name: nextclade_dataset
    dataset: sars-cov-2
    dataset_no-recomb: sars-cov-2-no-recomb
    tag: "2022-10-19T12:00:00Z"
    tag_no-recomb: "2022-10-19T12:00:00Z"

  # ---------------------------------------------------------------------------
  # exclude_clades    : (optional) Exclude strains that are recombinants of these clades
  - name: nextclade_recombinants
    exclude_clades:
      - "19" # From 2019
      - "20" # From 2020
      #- "21" # From 2021
      #- "22" # From 2022
      - "20A" # Non-VOC 2020
      - "20B" # Non-VOC 2020
      - "20C" # Non-VOC 2020
      - "20D" # Non-VOC 2020
      - "20E" # Non-VOC 2020
      - "20F" # Non-VOC 2020
      - "20G" # Non-VOC 2020
      - "20I" # Alpha
      - "20H" # Beta
      - "20J" # Gamma
      #- "21I" # Delta
      #- "21J" # Delta
      - "21C" # Episilon
      - "21D" # Eta
      - "21E" # Theta
      - "21B" # Kappa
      - "21G" # Lambda
      - "21H" # Mu
      #- "21K" # Omicron BA.1
      #- "21L" # Omicron BA.2

  # ---------------------------------------------------------------------------
  # exclude_negatives : true if sequences that are not recombinants (according to Nextclade) should be excluded from sc2rf analysis.
  #                   :   only set to true if there is at least 1 guaranteed recombinant sequence in your input!
  # max_name_length   : The maximum character length of strain names
  # sc2rf_args        : Additional arguments supplied to the program sc2rf
  # primers           : Path to primers, relative to sc2rf directory.
  # primers_name      : The name of the primer set to display in output.
  # mode              : List of named parameter sets to use for sc2rf. sc2rf will run multiple times independently
  #                   :   with the supplied command-line-args, and create intermediate ansi output as
  #                   :   ansi.<mode>.txt and stats.<mode>.csv and collated afterwards.
  #                   :   any number of modes can be supplied.
  #                   : The order of modes is important! The results of modes further down in the list
  #                   :   will override those higher up when results are collated in sc2rf_recombinants.
  - name: sc2rf
    exclude_negatives: false
    max_name_length: 50
    mode:
      # Lineage specific validation)
      - XA:              "--clades 20I 20E         --ansi --parents 2   --breakpoints 1-10 --unique 2 --max-ambiguous 20 --max-intermission-length 2 --max-intermission-count 3  --ignore-shared --mutation-threshold 0.25"
      - XB:              "--clades B.1.631 B.1.634 --ansi --parents 2   --breakpoints 1-10 --unique 5 --max-ambiguous 20 --max-intermission-length 2 --max-intermission-count 20 --ignore-shared --mutation-threshold 0.25"
      - XC:              "--clades 20I 21J 21I     --ansi --parents 2-3 --breakpoints 0-10 --unique 5 --max-ambiguous 20 --max-intermission-length 2 --max-intermission-count 3  --ignore-shared --mutation-threshold 0.25"
      - proposed808:     "--clades 21K B.1.438.1   --ansi --parents 2   --breakpoints 1-10 --unique 3 --max-ambiguous 20 --max-intermission-length 2 --max-intermission-count 3  --ignore-shared --mutation-threshold 0.25"
      - XAJ:             "--clades 22A 22C         --ansi --parents 2   --breakpoints 0-10 --unique 1 --max-ambiguous 20 --max-intermission-length 2 --max-intermission-count 3  --ignore-shared --mutation-threshold 0.25"
      - XAY:             "--clades 21I 21J 21K 21L --ansi --parents 2-4 --breakpoints 2-10 --unique 3 --max-ambiguous 20 --max-intermission-length 2 --max-intermission-count 20 --ignore-shared --mutation-threshold 0.25"
      - XBB:             "--clades BA.2.10 BA.2.75 --ansi --parents 2   --breakpoints 1-10 --unique 1 --max-ambiguous 20 --max-intermission-length 2 --max-intermission-count 3 --ignore-shared --mutation-threshold 0.25"
      # General (discovery and validation)
      - delta_omicron:   "--clades 21I 21J 21K 21L --ansi --parents 2-4 --breakpoints 0-10 --unique 1 --max-ambiguous 20 --max-intermission-length 2 --max-intermission-count 3  --ignore-shared --mutation-threshold 0.25"
      - omicron_omicron: "--clades 21K 21L 22A 22B --ansi --parents 2-4 --breakpoints 0-10 --unique 1 --max-ambiguous 20 --max-intermission-length 2 --max-intermission-count 3  --ignore-shared --mutation-threshold 0.25"
  # ---------------------------------------------------------------------------
  # min_len            : (optional) Ignore recombinant regions shorter than this
  # min_consec_allele  : (optional) Ignore recombinant regions with less than this number of consecutive alleles (both subs and ref)
  # max_breakpoint_len : (optional) Ignore recombinant breakpoints longer than this
  # max_breakpoints    : (optional) Exlude samples with greater than this number of parents
  # max_parents        : (optional) Exlude samples with greater than this number of breakpoints
  # motifs             : (optional, experimental) Path to a breakpoints motif file
  # dup_method         : (optional, experimental) Method for resolving duplicate results when multiple sc2rf modes generated postives
  #                    :  'first' : Retain positive results from first mode encountered (top in mode list)
  #                    :  'last'  : Retain positive results from last mode encountered (bottom in mode list)
  #                    :  'min_bp': Prioritize positive results with the fewest breakpoints.
  #                    :  'min_uncertainty': Prioritize positive results with the smallest breakpoint intervals.
  # auto_pass          : (optional) Samples with these lineage assignments by nextclade will
  #                      automatically be classified as 'positive', regardless of sc2rf results.
  - name: sc2rf_recombinants
    min_len: 500
    min_consec_allele: 3
    max_breakpoint_len:
    max_parents:
    max_breakpoints:
    motifs:
    dup_method: min_uncertainty
    auto_pass:
      - XN
      - XP
      - XAR
      - XAS
      - XAZ

  # ---------------------------------------------------------------------------
  # extra_cols : (Optional) list of metadata columns to output going forwards (aside from defaults of strain,date,country)
  - name: summary
    extra_cols:
    #  - gisaid_epi_isl
    #  - genbank_accession

  # ---------------------------------------------------------------------------
  # geo             : Column to use for a geographic summary (typically region, country, or division)
  # min_lineage_size: If a designated lineage has more than this number of sequences, investigate
  #                   whether it is a mimic (X*-like), based on the presence of private mutations.
  # min_private_muts: When checking for a mimic (X*-like), all sequences of the lineage must have at least
  #                   this many shared private mutations.
  - name: linelist
    geo: country
    min_lineage_size: 10
    min_private_muts: 3

  # ---------------------------------------------------------------------------
  # lag           : The number of weeks before the present where data is accurate (ex. 4). Used to plot a light grey box.
  # weeks         : The number of weeks to plot in retrospect (ex. 16)
  # min_date      : (Optional) The date to start plots at (ex. "2022-01-03"). Overrides the `weeks` parameter.
  # max_date      : (Optional) The date to end plots at (ex. "2022-04-25").
  # singletons    : "true" if singelton lineages (N=1) should be plotted and reported.
  # Note: the rule `plot` is also going to use the `geo` param of rule `linelist`, to plot recombinants by geographic location
  - name: plot
    weeks: 16
    lag: 4
    min_date:
    max_date:
    singletons: true

  # ---------------------------------------------------------------------------
  # template    : (Optional) path to a powerpoint template
  # Note: the rule `report` is also going to use the `geo` param of rule `linelist`, to summarize recombinants by geographic location
  - name: report
    template: "resources/template.pptx"

  # ---------------------------------------------------------------------------
  # expected    : path to expected linelist to validate results against
  - name: validate
    expected: "defaults/validation.tsv"
